#!/bin/sh

# Generated by ~/.config/tinty/hooks/apply.sh from tinty scheme: base16-catppuccin-macchiato
export COLOR_BACKGROUND=0xe024273a    # Base
export COLOR_FOREGROUND=0xe0cad3f5    # Text
export COLOR_DEFAULT=0xffcad3f5       # Text (full opacity)

export COLOR_ACCENT=0xe0f5a97f
export COLOR_ACCENT_BRIGHT=0xe0f5a97f

export COLOR_BLACK=0xe0363a4f
export COLOR_RED=0xe0ed8796
export COLOR_GREEN=0xe0a6da95
export COLOR_YELLOW=0xe0eed49f
export COLOR_ORANGE=0xe0f5a97f
export COLOR_BLUE=0xe08aadf4
export COLOR_MAGENTA=0xe0c6a0f6
export COLOR_CYAN=0xe08bd5ca
export COLOR_WHITE=0xe0cad3f5         # Text
