-- require("items.widgets.control_center")
require("items.widgets.bluetooth")
-- require("items.widgets.volume")
require("items.widgets.battery")
require("items.widgets.device_battery")
require("items.widgets.wifi")
-- require("items.widgets.weather")
require("items.widgets.cpu_and_temp")
-- require("items.widgets.front_app")
-- require("items.widgets.temperature")
-- require("items.widgets.cpu")
