#!/bin/sh
# Regenerates derived configs from the active tinty scheme.
# Invoked by the `hooks` array in ~/.config/tinted-theming/tinty/config.toml
# on every `tinty apply`.
#
# Currently handles:
#   - simple-bar: lib/styles/pywal/pywal.js (consumed by pywal-colors.js
#     when WITH_PYWAL is enabled in lib/styles/theme.js)
#   - ~/.config/colors.sh (COLOR_* environment exports)
#   - Zed: swaps the selected theme name in settings.json to the applied
#     tinted-zed theme (JSONC-safe: line-targeted substitution)
#
# Ghostty and btop are handled by their [[items]] hooks in config.toml.
set -eu

TINTY_BIN="${TINTY_BIN:-tinty}"
command -v "$TINTY_BIN" >/dev/null 2>&1 || TINTY_BIN="$HOME/.local/bin/tinty"

DATA_DIR="${TINTY_DATA_DIR_PATH:-$HOME/.local/share/tinted-theming/tinty}"
SIMPLE_BAR_PYWAL="$HOME/.config/simple-bar/lib/styles/pywal"
COLORS_SH="$HOME/.config/colors.sh"

SCHEME=$("$TINTY_BIN" current) # e.g. base16-catppuccin-macchiato
SYSTEM=${SCHEME%%-*}           # base16 | base24
NAME=${SCHEME#"$SYSTEM"-}
YAML="$DATA_DIR/repos/schemes/$SYSTEM/$NAME.yaml"

if [ ! -f "$YAML" ]; then
  echo "apply.sh: scheme file not found: $YAML" >&2
  exit 1
fi

get() {
  sed -n "s/^[[:space:]]*$1:[[:space:]]*[\"']\{0,1\}\(#[0-9A-Fa-f]\{6\}\).*/\1/p" "$YAML" |
    head -n 1
}

BASE00=$(get base00)
BASE01=$(get base01)
BASE02=$(get base02)
BASE05=$(get base05)
BASE08=$(get base08)
BASE09=$(get base09)
BASE0A=$(get base0A)
BASE0B=$(get base0B)
BASE0C=$(get base0C)
BASE0D=$(get base0D)
BASE0E=$(get base0E)

# Fail loudly rather than writing empty colors if extraction breaks.
: "${BASE00:?apply.sh: could not extract palette from $YAML}"

# --- simple-bar ----------------------------------------------------------
cat >"$SIMPLE_BAR_PYWAL/pywal.js" <<EOF
// Generated by ~/.config/tinty/hooks/apply.sh from tinty scheme: $SCHEME
export const variables = {
  main: "$BASE00",
  mainAlt: "$BASE01",
  minor: "$BASE02",
  accent: "$BASE0A",
  red: "$BASE08",
  green: "$BASE0B",
  yellow: "$BASE0A",
  orange: "$BASE09",
  blue: "$BASE0D",
  magenta: "$BASE0E",
  cyan: "$BASE0C",
};
EOF

# --- colors.sh -----------------------------------------------------------
cat >"$COLORS_SH" <<EOF
#!/bin/sh

# Generated by ~/.config/tinty/hooks/apply.sh from tinty scheme: $SCHEME
export COLOR_BACKGROUND=0xe0${BASE00#\#}    # Base
export COLOR_FOREGROUND=0xe0${BASE05#\#}    # Text
export COLOR_DEFAULT=0xff${BASE05#\#}       # Text (full opacity)

export COLOR_ACCENT=0xe0${BASE09#\#}
export COLOR_ACCENT_BRIGHT=0xe0${BASE09#\#}

export COLOR_BLACK=0xe0${BASE02#\#}
export COLOR_RED=0xe0${BASE08#\#}
export COLOR_GREEN=0xe0${BASE0B#\#}
export COLOR_YELLOW=0xe0${BASE0A#\#}
export COLOR_ORANGE=0xe0${BASE09#\#}
export COLOR_BLUE=0xe0${BASE0D#\#}
export COLOR_MAGENTA=0xe0${BASE0E#\#}
export COLOR_CYAN=0xe0${BASE0C#\#}
export COLOR_WHITE=0xe0${BASE05#\#}         # Text
EOF

# --- Ghostty -------------------------------------------------------------
# Ghostty (1.3.1, macOS) has NO config-file auto-watch: the only runtime
# reload is manual (cmd+shift+,) or the reload_config keybind. We write the
# theme under its scheme name and rewrite `theme = <scheme>` in the main
# config so the NEXT manual reload (or new window) picks it up.
# Optionally, drive the keystroke automatically — requires Accessibility
# permission for the calling terminal, and activates Ghostty (focus steal).
# Enable with: export TINTY_GHOSTTY_AUTO_RELOAD=1
GHOSTTY_DIR="$HOME/.config/ghostty"
GHOSTTY_SRC="$DATA_DIR/repos/tinted-ghostty/themes/ghostty/$SCHEME"
if [ -f "$GHOSTTY_SRC" ]; then
  cp -f "$GHOSTTY_SRC" "$GHOSTTY_DIR/themes/$SCHEME"
  GHOSTTY_CONFIG="$GHOSTTY_DIR/config"
  if ! grep -q "^theme = $SCHEME\$" "$GHOSTTY_CONFIG"; then
    GHOSTTY_TMP=$(mktemp)
    sed "s/^theme = .*/theme = $SCHEME/" "$GHOSTTY_CONFIG" >"$GHOSTTY_TMP"
    cat "$GHOSTTY_TMP" >"$GHOSTTY_CONFIG"
    rm -f "$GHOSTTY_TMP"
  fi
  if [ "${TINTY_GHOSTTY_AUTO_RELOAD:-0}" = "1" ]; then
    osascript \
      -e 'tell application "Ghostty" to activate' \
      -e 'tell application "System Events" to keystroke "," using {command down, shift down}' \
      >/dev/null 2>&1 || true
  fi
fi

# --- Zed -----------------------------------------------------------------
# Fixed theme identity: copy the scheme into tinty.json with its internal
# names patched to "Tinty", and select "Tinty" for the matching appearance
# in settings.json. settings.json therefore stops changing after first
# setup; only tinty.json content changes between schemes.
ZED_SRC="$DATA_DIR/repos/tinted-zed/themes/$SCHEME.json"
ZED_DST="$HOME/.config/zed/themes/tinty.json"
if [ -f "$ZED_SRC" ] && command -v python3 >/dev/null 2>&1; then
  cp -f "$ZED_SRC" "$ZED_DST"
  sed -i '' 's/"name": "Base16[^"]*"/"name": "Tinty"/g' "$ZED_DST"
  ZED_APPEARANCE=$(python3 -c "
import json, sys
print(json.load(open(sys.argv[1]))['themes'][0]['appearance'])
" "$ZED_DST")
  # Skip the rewrite when already selected: perl -pi renames the file,
  # which would needlessly churn (and could detach) Zed's watcher.
  if ! grep -q "\"$ZED_APPEARANCE\": \"Tinty\"" "$HOME/.config/zed/settings.json"; then
    MODE="$ZED_APPEARANCE" perl -pi -e \
      's/("$ENV{MODE}": ")[^"]*(")/${1}Tinty${2}/' \
      "$HOME/.config/zed/settings.json"
  fi
fi