[general]
framerate = 30
bars = 8
autosens = 1

[input]
method = portaudio
source = "BlackHole 2ch"

[output]
method = raw
data_format = ascii
ascii_max_range = 8
bar_delimiter = 32
channels = mono
mono_option = average

